### ISSUE TITLE
Please add some instructions?

### ISSUE THREAD

**Issue by daicain** [l3uddz/drive_strm#9]
This could be your personal project, but some of us noobs are not really sure, so it'd be great to have some instructions or something to help

**Comment by desimaniac** [comment]
It's not completed yet. Hence that's why it's in a dev branch. We usually create guides once something hits master branch. No point in documenting something that may change in another update.

**Comment by desimaniac** [comment]
Also, if you've seen other projects around here, you'll know we don't keep things to just ourselves..

**Comment by desimaniac** [comment]
And the instructions have been mentioned on Discord.

**Comment by qazero** [comment]
Could you please link me to the discord? I am very much interested in this as well and would like to see the instructions. Thanks :)

**Comment by desimaniac** [comment]
Forgot the readme hadn't been made yet ... 

https://discord.io/cloudbox
